# Generated by Django 4.2.11 on 2024-04-04 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_delete_prfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid Iranian phone number", regex="^09\\d{9}$"
                    )
                ],
            ),
        ),
    ]
