# Generated by Django 4.2.11 on 2024-04-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="ProductCategory",
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="/defult/product-image.png", upload_to="product/img/"
            ),
        ),
    ]
