# Generated by Django 4.2.11 on 2024-04-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_rename_category_productcategory_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="descrption",
            new_name="description",
        ),
    ]
